// Code generated by girgen. DO NOT EDIT.

package gnomebluetooth

import (
	_ "runtime/cgo"
)

// #cgo pkg-config: gnome-bluetooth-1.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
import "C"
